service: user-service

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    USER_TABLE: user
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
         path: user
         method: post
  getUser:
    handler: handler.getUser
    events:
      - http:
         path: user
         method: get
  getUserByEmail:
    handler: handler.getUserByEmail
    events:
      - http:
         path: user/{email}
         method: get
         request:
          parameters:
            paths:
              email: true
  updateUser:
    handler: handler.updateUser
    events:
      - http:
         path: user
         method: put
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
         path: user
         method: delete
  login:
    handler: handler.login
    events:
      - http:
         path: login
         method: post

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "email"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "email"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.USER_TABLE}